// Common
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

// Status Code
export const SERVER_FAILED = 'SERVER_FAILED';
export const NO_RESPONSE = 'NO_RESPONSE';
export const FORBIDDEN = 'FORBIDDEN';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const NOT_FOUND = 'NOT_FOUND';

// Session
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// ActivityAreas
export const RECEIVE_ACTIVITY_AREAS = 'RECEIVE_ACTIVITY_AREAS';
export const RECEIVE_ACTIVITY_AREA = 'RECEIVE_ACTIVITY_AREA';

// Laboratory
export const RECEIVE_LABORATORY = 'RECEIVE_LABORATORY';
export const UPDATE_LABORATORY = 'UPDATE_LABORATORY';

// Standards
export const RECEIVE_STANDARDS = 'RECEIVE_STANDARDS';
export const INSERT_STANDARD = 'INSERT_STANDARD';
export const UPDATE_STANDARD = 'UPDATE_STANDARD';
export const UPDATE_ALL_STANDARDS = 'UPDATE_ALL_STANDARDS';
export const REMOVE_STANDARD = 'REMOVE_STANDARD';

// Experiment Classes
export const RECEIVE_EXPERIMENT_CLASSES = 'RECEIVE_EXPERIMENT_CLASSES';

// Experiments
export const RECEIVE_EXPERIMENTS = 'RECEIVE_EXPERIMENTS';
export const INSERT_EXPERIMENT = 'INSERT_EXPERIMENT';
export const UPDATE_EXPERIMENT = 'UPDATE_EXPERIMENT';
export const UPDATE_ALL_EXPERIMENTS = 'UPDATE_ALL_EXPERIMENTS';
export const REMOVE_EXPERIMENT = 'REMOVE_EXPERIMENT';

// Products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const INSERT_PRODUCT = 'INSERT_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_ALL_PRODUCTS = 'UPDATE_ALL_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
